name: mautic_tracking_api
description: API to Monitoring and Tracking Users using Mautic for Dart and Flutter
version: 1.0.2
homepage: https://github.com/powerticmkt/dart-mautic-tracking-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0
  http: ^0.12.0+4
